import Head from 'next/head'
import {Inter} from 'next/font/google'
import Banner from "@/components/banner/Banner";
import Navbar from "@/components/navbar/Navbar";
import Card from "@/components/card/Card";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Netflix Clone</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h2>Netflix</h2>
                <Navbar username='elliottpolite@gmail.com'/>
                <Banner
                    title="NETFLIX ORIGINAL SERIES"
                    subtitle="Stranger Things"
                    imgUrl="/static/genericImage.jpg"
                />
                <Card imgUrl='/static/genericImage.jpg' size='small' />
                <Card imgUrl='/static/genericImage.jpg' size='medium' />
                <Card imgUrl='/static/genericImage.jpg' size='large' />

            </main>
        </>
    )
}
