import React from 'react';
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/login.module.css";
import Image from "next/image";

const Login = () => {
    const [email, setEmail] = React.useState('');
    const [userMsg, setUserMsg] = React.useState('');


    const resetUserMsg = () => {
        setUserMsg('');
    };


    const handleEmailInputChange = (event) => {
        resetUserMsg();
        setEmail(event.target.value);
    };


    const handleEmailLogin = (event) => {
        event.preventDefault();
        if (email === '') {
            setUserMsg('Please enter your email address');
        }
    };


    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix SignIn</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <header className={styles.header}>
                <div className={styles.headerWrapper}>
                    <Link href='/' className={styles.logoLink}>
                        <div className={styles.logoWrapper}>
                            <Image src='/static/netflix.svg' alt='netflix logo' width='112' height='32'/>
                        </div>
                    </Link>
                </div>
            </header>

            <main className={styles.main}>
                <div className={styles.mainWrapper}>
                    <h1 className={styles.signinHeader}>Sign In</h1>
                    <input className={styles.emailInput} onChange={handleEmailInputChange} type="text" placeholder='Email Address'/>
                    <p className={styles.userMsg}>
                        {userMsg}
                    </p>
                    <button className={styles.loginBtn} onClick={handleEmailLogin}>Sign In</button>
                </div>
            </main>
        </div>
    );
};

export default Login;